/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file is auto-generated
#pragma once

#if CONFIG_SLAVE_IDF_TARGET_ESP32
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32

#if CONFIG_SLAVE_IDF_TARGET_ESP32S2
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32S2

#if CONFIG_SLAVE_IDF_TARGET_ESP32C3
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32C3

#if CONFIG_SLAVE_IDF_TARGET_ESP32S3
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32S3

#if CONFIG_SLAVE_IDF_TARGET_ESP32C2
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32C2

#if CONFIG_SLAVE_IDF_TARGET_ESP32C6
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32C6

#if CONFIG_SLAVE_IDF_TARGET_ESP32H2
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32H2

#if CONFIG_SLAVE_IDF_TARGET_ESP32P4
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32P4

#if CONFIG_SLAVE_IDF_TARGET_ESP32C5
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32C5

#if CONFIG_SLAVE_IDF_TARGET_ESP32C61
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32C61

#if CONFIG_SLAVE_IDF_TARGET_ESP32H21
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32H21

#if CONFIG_SLAVE_IDF_TARGET_ESP32H4
#define CONFIG_ESP_WIFI_REMOTE_ENABLED 1
#define CONFIG_ESP_WIFI_REMOTE_LIBRARY_HOSTED 1
#endif // CONFIG_SLAVE_IDF_TARGET_ESP32H4
